language: java
sudo: required
addons:
    apt:
        packages:
            - python3
            - python3-dev
jdk:
    - openjdk8
    - oraclejdk8
    - oraclejdk9
before_script:
    - wget https://bootstrap.pypa.io/get-pip.py
    - sudo python3 get-pip.py
    - rm get-pip.py
script:
    - ./travis.sh
